django_restframework/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^index/', views.index),
    url(r'^hello/', views.HelloView.as_view(msg='hhh')),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^blog/', views.BlogListView.as_view(), name='blog'),
    url(r'^guess/', views.guess),
    url(r'^search/', views.search),
    url(r'^getlogs/', views.get_log),
    url(r'^upload/', views.UploadView.as_view(), name='upload'),  # 上传文件
    url(r'^geticon/', views.get_icon),

]

django_restframework/django_restframework/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from DRF.urls import router

urlpatterns = [
    url(r'', include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='app')),
    url(r'^drf/', include('DRF.urls', namespace='drf')),
    url(r'^drf2/', include('DRF2.urls', namespace='drf2')),
    url(r'^drf3/', include('DRF3.urls', namespace='drf3')),
]

django_restframework/App/models.py
from django.db import models


# Create your models here.
class Blog(models.Model):
    b_title = models.CharField(max_length=32)
    b_content = models.TextField()


class RequestLog(models.Model):
    r_ip = models.CharField(max_length=32)
    r_time = models.FloatField(default=0)


class Student(models.Model):
    s_name = models.CharField(max_length=16)
    s_pic = models.ImageField(upload_to='s_icons')

django_restframework/templates/blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客列表</title>
</head>
<body>
<h2>今日热门</h2>
<ul>
    {% for blog in blog_list %}
        <li>{{ blog.b_title }}</li>
    {% endfor %}
    
</ul>
</body>
</html>

django_restframework/templates/imageshow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图片显示</title>
</head>
<body>
<img src="{{ image_url }}" alt="头像">
</body>
</html>

django_restframework/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模板首页</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
<h2>模板首页</h2>
</body>
</html>

django_restframework/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
</head>
<body>

<input type="text" placeholder="请输入用户名">
<input type="submit" value="提交">
</body>
</html>

django_restframework/templates/logs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logs</title>
</head>
<body>
<ul>
    {% for log in page.object_list %}
        <li>{{ log.r_ip }}</li>
    {% endfor %}

</ul>
</body>
</html>

django_restframework/templates/up_load.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传文件</title>
</head>
<body>
<form action="{% url 'app:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="username" placeholder="请输入用户名">
    <input type="file" name="icon">
    <input type="submit" value="提交">
</form>
</body>
</html>